export default function Table(){
    return(
        <>
            <table>
                <tr>
                    <th></th>
                    <th>name</th>
                    <th>price</th>
                    <th>open</th>
                    <th>heigh</th>
                    <th>low</th>
                    <th>close</th>
                    <th>chg</th>
                    <th>chg%</th>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
        </>
    )
}